### ISSUE TITLE
Unexpected error running initialize() for a_group

### ISSUE THREAD

**Issue by CoReYeDe** [ReneTode/My-AppDaemon#11]
Hi.
i get the Error: 
KeyError: 'sensor'

AppDaemon is running and my apps.yaml looks like:

a_group:
  module: groups
  class: create_group
  name: TestSensorGroup
  device_type: sensor
  entity_part: "Briefkasten"
  entities:
    - sensor.Briefkasten
  hidden: False
  view: True
  assumed_state: False
  friendly_name: Last Updates
  nested_view: True #creates a second group inside a viewed group   

Home Assistant Version:
HASS: Connected to Home Assistant 0.77.3

![image](https://user-images.githubusercontent.com/22613068/45413835-63b6f480-b67a-11e8-8c3f-8bccc8171a60.png)

**Comment by ReneTode** [comment]
sorry that i missed this.

the problem is that this app isnt rewritten for AD 3.0

you need to change this:
```
import appdaemon.appapi as appapi

class create_group(appapi.AppDaemon):
```
to this:
```
import appdaemon.plugins.hass.hassapi as hass

class create_group(hass.Hass):
```

**Comment by CoReYeDe** [comment]
Thanks.. this resolve the Problem
