### ISSUE TITLE
Minor Typo in Gauges

### ISSUE THREAD

**Issue by Twit123** [ReneTode/My-AppDaemon#5]
Hi,

wasn't sure where to post this, here or on HA forum.

There is a minor typo in the instructions for gauges which took me a while to try figure out.

It says to drop the canvas-gauges into a folder called gauges but the the example for the variables.yaml point to a folder called gauge with no s. 

**"to activate the temperature and radial widgets you need to download canvas gauges that can be found here: https://github.com/Mikhus/canvas-gauges install that in the directory conf/custom_css/gauges in the variables.yaml from my waterdropsskill are the lines that point to that lib. if you want to use them in your own skin then create these 2 lines:

 - <script src="/custom_css/gauge/gauge.min.js"></script>
 - <link rel="stylesheet" href="/custom_css/gauge/fonts/fonts.css">"**

Thanks for all your awesome work and I love the gauges

Cheers

Si

**Comment by ReneTode** [comment]
thx. changed it in the readme.
