### ISSUE TITLE
Help to install

### ISSUE THREAD

**Issue by pricard32** [ReneTode/My-AppDaemon#6]
I have some difficulties to install theses widgets..
Maybe it's because english isn't my first language that I have issue to understand the Readme file,,,

But step by step, do I only have to copy and paste these folders on the main directory of AppDaemon (hadaemon)?

So i'll have ; app / compiled / custom_css / custom_widgets / dashboards / appdaemon.yaml ; on this folder ?

Am I wrong ? it's says on the conf folder, but I don't see it ?

Thanks you,

Paul

**Comment by ReneTode** [comment]
the conf folder is where your configuration files are
it should be:
conf/compiled
conf/custom_css
conf/custom_widgets
conf/dashboards
conf/apps.yaml
conf/appdaemon.yaml

**Comment by pricard32** [comment]
I've read some topic and it seems to not work with the Hass.io version of Home Assistant, possible ?

**Comment by ReneTode** [comment]
if you use the right appdaemon addon, then it should work fine.
