### ISSUE TITLE
R2 needs variation for MotionDetect and documentation clarification

### ISSUE THREAD

**Issue by hawkeyeP** [ReneTode/My-AppDaemon#7]
Python had me running around in circles today with inaccurate foscam access denied errors for the Foscam R2 camera.  The error messages were making me think I had a write permission problem but it had nothing to do with that.

I didn't find anything that addresses this problem directly here or in the forum but the solution was to make a couple changes in apps/foscam.py for the R2:

getMotionDetectConfig needs to be getMotionDetectConfig1
setMotionDetectConfig needs to be setMotionDetectConfig1

Can this be added to the documentation or a variation added to the code?

The documentation is vague about needing to add the input_selects to HA as they are not in your example 0.55 HA file (add_to_ha_configuration) just references to them in the group section.

Also using:   dash_compile_on_start: 1 in appdaemon.yaml was very useful while troubleshooting the install. 

I hope these are helpful additions to the documentation.

**Comment by ReneTode** [comment]
thx for the feedback.

i added the input selects to the config (missed that somehow) 
i added a footnote for the R2 cam and will make a change in the future to change it automaticly.
